### ISSUE TITLE
Synchronize api.backdropcms.org indexed code base

### ISSUE THREAD

**Issue by cellear** [backdrop-ops/api.backdropcms.org#4] opened 2014-09-03 20:15 UTC
api.backdropcms.org is only useful if it documents that existing Backdrop code base.  At the moment there's no mechanism for updating it, so the code it demonstrates is from May -- it doesn't have the backdrop_\* functions, for example!

It does have the Drupal Compatibility Layer, however, so maybe it's just incompletely indexed:
   http://api.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/group/drupal_compatibility/1

**Comment by serundeputy** [comment] 2019-06-11 18:23
@larsdesigns can you check that these (https://github.com/backdrop-ops/api.backdropcms.org/issues/4#issuecomment-54397100) cron jobs are set up on the new server?

**Comment by BWPanda** [comment] 2019-09-27 17:40
https://github.com/backdrop-ops/api.backdropcms.org/issues/67 had a request to update the codebase so new functions would be available on the API site. Marked as a duplicate of this one.

**Comment by larsdesigns** [comment] 2019-10-15 21:40
@serundeputy, Probably old news but these cron jobs are on the new host: 

```
0 * * * * cd /home/api/backdrop-code-to-index; /usr/bin/git pull
0 * * * * cd /home/api/backdrop-code-to-index/modules/examples; /usr/bin/git pull
*/5 * * * * wget -O - -q -t 1 https://api.backdropcms.org/core/cron.php?cron_key=QXf7y8JYO8XD_qw4KhyOzErHNdo2OdG2PxOkDkL1Oks
```

**Comment by BWPanda** [comment] 2019-10-16 04:09
@larsdesigns Are _now_ on the new host, or were already?

`field_get_value()` is in core (https://github.com/backdrop/backdrop/blob/1ca102b0579848b6f9d7906d8d226089fcbd53ea/core/modules/field/field.module#L698) but isn't showing up on the API site still...

**Comment by larsdesigns** [comment] 2019-10-17 20:56
@BWPanda, The jobs were already there.

**Comment by BWPanda** [comment] 2019-10-18 00:14
@larsdesigns Thanks for checking on this.

The issue remains however, so maybe its an indexing problem...? @serundeputy @cellear @larsdesigns are you able to look into this to work out why functions still aren't showing up?

@cellear Do you have access to this server still? If so, we should add your name to https://backdropcms.org/user-guide/roles-responsibilities-and-points-contact

**Comment by larsdesigns** [comment] 2019-11-01 23:24
@BWPanda, Thank you for testing that. I am mostly involved with the infrastructure and have not been updating the applications  (sites). However, I suppose if your pull request is approved I can perform the update. I will need to check with the team though to double check the procedure.

**Comment by quicksketch** [comment] 2019-11-01 23:45
I checked on this and it seems that the cloned Git repository that the API site uses had a merge conflict for some reason.

```
api@www2:~/backdrop-code-to-index$ git pull
Updating 8b6a3f752..faead38e3
error: Your local changes to the following files would be overwritten by merge:
```

I just had it revert to the latest code (`git checkout .`) and discard the local changes. And now it's updating again. It may take a few cron runs for all new functions to be indexed.

**Comment by larsdesigns** [comment] 2019-11-01 23:52
@quicksketch Awesome, thank you so much for sorting that out.

**Comment by quicksketch** [comment] 2019-11-02 01:00
I'm now seeing the new code specifically called out as missing before now showing up:

https://api.backdropcms.org/api/backdrop/core%21modules%21field%21field.module/function/field_get_value/1

So I think we're set here.

**Closed by quicksketch** 2019-11-02 01:00 UTC
Labels: type - bug

**Comment by BWPanda** [comment] 2019-11-02 06:28
@larsdesigns @quicksketch Is maybe using the [`-f`](https://www.git-scm.com/docs/git-pull#Documentation/git-pull.txt--f) option for `git pull` here a good idea to avoid future issues like this?
