### ISSUE TITLE
Missing field_get_value / field_get_values functions

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/api.backdropcms.org#67] opened 2019-08-16 16:43 UTC
I thought the docblock would be picked up automatically, so perhaps need to update the code reference to get the latest API changes.

**Comment by BWPanda** [comment] 2019-09-27 17:39
Marking as a duplicate of https://github.com/backdrop-ops/api.backdropcms.org/issues/4.

**Closed by BWPanda** 2019-09-27 17:39 UTC
