### ISSUE TITLE
Create Module API Corrections

### ISSUE THREAD

**Issue by twmfc** [backdrop-ops/api.backdropcms.org#35] opened 2016-08-31 15:52 UTC
Hi,
I've just been reviewing Creating Modules section within the Backdrop CMS API documentation, specifically [https://api.backdropcms.org/modules] and noticed a few incorrect metion of themes and other issues that I've tried to capture here:

**Section: Contents of a module directory**

Current:

Modules are comprised of a module directory, usually named after the main module it contains, containing files and directories. Core theme directories are found in the BACKDROP_ROOT/core/modules directory; contributed themes in the BACKDROP_ROOT/modules directory. A module directory may have the following example structure (although not all of these are required, as explained below):

Proposed:

Modules are comprised of a module directory, usually named after the main module it contains, containing files and directories. Core module directories are found in the BACKDROP_ROOT/core/modules directory and contributed modules in the BACKDROP_ROOT/modules directory. A module directory may have the following example structure (although not all of these are required, as explained below):

**Section: The .info file**

Current:

All modules require an .info file to tell Backdrop about the module. Contents of a module .info file may vary and are explained in greater detail further on. The internal name of the module is also derived from this file. For example, if it is named "my_module.info", then Backdrop will see the name of the theme as "my_module".

Proposed:

All modules require an .info file to tell Backdrop about the module. Contents of a module .info file may vary and are explained in greater detail further on. The internal name of the module is also derived from this file. For example, if it is named "my_module.info", then Backdrop will see the name of the module as "my_module".

**Section: required (Optional)
                required = TRUE**

Current:

Mdules and themes may specify that they are absolutely required and should never be disabled by adding required = TRUE. These modules will be enabled automatically during install. In most cases it should only be used with the Backdrop core required modules (e.g. Node, User, etc.).

Proposed:

Modules and themes may specify that they are absolutely required and should never be disabled by adding required = TRUE. These modules will be enabled automatically during install. In most cases it should only be used with the Backdrop core required modules (e.g. Node, User, etc.).

**Section: About hooks (4th paragraph)**

Hooks are how modules can interact with the core code of Backdrop. They make it possible for a module to define new urls and pages within the site (hook_menu), to add content to pages (hook_block), to set up custom database tables (hook_schema), and more. This page lists the hooks provided in the core and modules can also define their own hooks.

**Section: About hooks (5th paragraph)**

Current:

Hooks occur at various points in the thread of execution, where Backdrop seeks contributions from all the enabled modules. For example, when a user visits a help page on a Backdrop site, as Backdrop prepares to save a node it will give each module a chance to alter the $node object. It does this by scanning all the module code for functions that have the name MYMODULE_node_update($node), where "MYMODULE" is the module's name, e.g., the block module's node update hook is called block_node_update. MYMODULE can then act on the $node object which is being updated.

Proposed:

Hooks occur at various points in the thread of execution, where Backdrop seeks contributions from all the enabled modules; for example as Backdrop prepares to save a node it will give each module a chance to alter the $node object. It does this by scanning all the module code for functions that have the name MYMODULE_node_update($node), where "MYMODULE" is the module's name, e.g., the block module's node update hook is called block_node_update. MYMODULE can then act on the $node object which is being updated.

**Comment by serundeputy** [comment] 2016-10-22 16:38
duplicate of #34 ?

**Comment by serundeputy** [comment] 2017-02-20 15:18
Thanks for pointing that out @twmfc 
This was addressed and updated in https://github.com/backdrop-ops/api.backdropcms.org/issues/34 

closing.

**Closed by serundeputy** 2017-02-20 15:18 UTC
